// ACP preset metadata adapted from Paseo d7c7044 (Apache-2.0).
// See third-party/paseo-LICENSE. Presets do not imply an installed or authenticated CLI.
import type { ProviderPreset } from "./providers.ts";
export const providerPresets: ProviderPreset[] = [
  {
    id: "codex",
    label: "Codex",
    engine: "codex",
    command: ["codex"],
    enabled: true,
    install: {
      kind: "npm",
      package: "@openai/codex@0.154.0",
      bin: "codex",
    },
    installLink: "https://developers.openai.com/codex/cli/",
  },
  {
    id: "claude",
    label: "Claude Code",
    engine: "claude",
    command: ["claude"],
    enabled: true,
    install: {
      kind: "npm",
      package: "@anthropic-ai/claude-code@2.1.268",
      bin: "claude",
    },
    installLink: "https://code.claude.com/docs/en/overview",
  },
  {
    id: "opencode",
    label: "OpenCode",
    engine: "opencode",
    command: ["opencode"],
    enabled: true,
    install: {
      kind: "npm",
      package: "opencode-ai@1.18.30",
      bin: "opencode",
    },
    installLink: "https://opencode.ai/docs/",
  },
  {
    id: "pi",
    label: "Pi",
    engine: "pi",
    command: ["pi"],
    enabled: false,
    install: {
      kind: "npm",
      package: "@earendil-works/pi-coding-agent@0.85.1",
      bin: "pi",
    },
    installLink: "https://github.com/badlogic/pi-mono/tree/main/packages/coding-agent",
  },
  {
    id: "copilot",
    label: "GitHub Copilot",
    engine: "acp",
    command: ["copilot", "--acp"],
    enabled: false,
    install: {
      kind: "npm",
      package: "@github/copilot@1.0.83",
      bin: "copilot",
    },
    installLink: "https://docs.github.com/en/copilot/how-tos/copilot-cli",
  },
  {
    id: "omp",
    label: "OMP",
    engine: "omp",
    command: ["omp"],
    enabled: false,
    install: {
      kind: "npm",
      package: "@oh-my-pi/pi-coding-agent@18.1.17",
      bin: "omp",
    },
    installLink: "https://github.com/can1357/oh-my-pi",
  },
  {
    id: "acp-agoragentic-acp",
    label: "Agoragentic",
    engine: "acp",
    command: ["npx", "-y", "agoragentic-mcp@1.3.6", "--acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "agoragentic-mcp@1.3.6",
    },
    installLink: "https://agoragentic.com",
  },
  {
    id: "acp-amp-acp",
    label: "Amp",
    engine: "acp",
    command: ["amp-acp"],
    enabled: false,
    installLink: "https://github.com/tao12345666333/amp-acp",
  },
  {
    id: "acp-auggie",
    label: "Auggie CLI",
    engine: "acp",
    command: ["npx", "-y", "@augmentcode/auggie@0.33.0", "--acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "@augmentcode/auggie@0.33.0",
    },
    installLink: "https://www.augmentcode.com/",
    env: {
      AUGMENT_DISABLE_AUTO_UPDATE: "1",
    },
  },
  {
    id: "acp-autohand",
    label: "Autohand Code",
    engine: "acp",
    command: ["npx", "-y", "@autohandai/autohand-acp@0.2.1"],
    enabled: false,
    install: {
      kind: "npx",
      package: "@autohandai/autohand-acp@0.2.1",
    },
    installLink: "https://www.autohand.ai/cli/",
  },
  {
    id: "acp-cline",
    label: "Cline",
    engine: "acp",
    command: ["npx", "-y", "cline@3.0.46", "--acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "cline@3.0.46",
    },
    installLink: "https://cline.bot/cli",
  },
  {
    id: "acp-codebuddy-code",
    label: "Codebuddy Code",
    engine: "acp",
    command: ["codebuddy", "--acp"],
    enabled: false,
    installLink: "https://www.codebuddy.cn/cli/",
  },
  {
    id: "acp-codewhale",
    label: "CodeWhale",
    engine: "acp",
    command: ["codewhale", "serve", "--acp"],
    enabled: false,
    installLink: "https://codewhale.net/",
  },
  {
    id: "acp-cortex-code",
    label: "Cortex Code",
    engine: "acp",
    command: ["cortex", "acp", "serve"],
    enabled: false,
    installLink: "https://docs.snowflake.com/en/user-guide/cortex-code/cortex-code-cli",
  },
  {
    id: "acp-corust-agent",
    label: "Corust Agent",
    engine: "acp",
    command: ["corust-agent-acp"],
    enabled: false,
    installLink: "https://github.com/Corust-ai/corust-agent-release/releases",
  },
  {
    id: "acp-crow-cli",
    label: "crow-cli",
    engine: "acp",
    command: ["crow-cli", "acp"],
    enabled: false,
    installLink: "https://crow-ai.dev/",
  },
  {
    id: "acp-cursor",
    label: "Cursor",
    engine: "acp",
    command: ["cursor-agent", "acp"],
    enabled: false,
    installLink: "https://docs.cursor.com/en/cli/overview",
  },
  {
    id: "acp-deepagents",
    label: "DeepAgents",
    engine: "acp",
    command: ["npx", "-y", "deepagents-acp@0.1.20"],
    enabled: false,
    install: {
      kind: "npx",
      package: "deepagents-acp@0.1.20",
    },
    installLink: "https://docs.langchain.com/oss/javascript/deepagents/overview",
  },
  {
    id: "acp-devin",
    label: "Devin CLI",
    engine: "acp",
    command: ["devin", "acp"],
    enabled: false,
    installLink: "https://cli.devin.ai/docs",
  },
  {
    id: "acp-dimcode",
    label: "DimCode",
    engine: "acp",
    command: ["npx", "-y", "dimcode@0.2.36", "acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "dimcode@0.2.36",
    },
    installLink: "https://dimcode.dev/docs/acp.html",
  },
  {
    id: "acp-dirac",
    label: "Dirac",
    engine: "acp",
    command: ["npx", "-y", "dirac-cli@0.4.22", "--acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "dirac-cli@0.4.22",
    },
    installLink: "https://dirac.run",
  },
  {
    id: "acp-factory-droid",
    label: "Factory Droid",
    engine: "acp",
    command: ["npx", "-y", "droid@0.179.0", "exec", "--output-format", "acp-daemon"],
    enabled: false,
    install: {
      kind: "npx",
      package: "droid@0.179.0",
    },
    installLink: "https://factory.ai/product/cli",
    env: {
      DROID_DISABLE_AUTO_UPDATE: "true",
      FACTORY_DROID_AUTO_UPDATE_ENABLED: "false",
    },
    params: {
      supportsMcpServers: false,
    },
  },
  {
    id: "acp-fast-agent",
    label: "fast-agent",
    engine: "acp",
    command: ["uvx", "--from", "fast-agent-acp==0.9.22", "fast-agent-acp", "-x"],
    enabled: false,
    installLink: "https://fast-agent.ai/acp/",
  },
  {
    id: "acp-gemini",
    label: "Gemini CLI",
    engine: "acp",
    command: ["npx", "-y", "@google/gemini-cli@0.52.0", "--acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "@google/gemini-cli@0.52.0",
    },
    installLink: "https://geminicli.com",
  },
  {
    id: "acp-gjc",
    label: "Gajae Code",
    engine: "acp",
    command: ["gjc", "acp"],
    enabled: false,
    installLink: "https://gajae-code.com",
    env: {
      GJC_ACP_PERMISSION_MODE: "prompt",
    },
  },
  {
    id: "acp-glm-acp-agent",
    label: "GLM Agent",
    engine: "acp",
    command: ["npx", "-y", "glm-acp-agent@1.3.0"],
    enabled: false,
    install: {
      kind: "npx",
      package: "glm-acp-agent@1.3.0",
    },
    installLink: "https://github.com/stefandevo/glm-acp-agent",
  },
  {
    id: "acp-goose",
    label: "goose",
    engine: "acp",
    command: ["goose", "acp"],
    enabled: false,
    installLink: "https://block.github.io/goose/",
  },
  {
    id: "acp-grok",
    label: "Grok",
    engine: "acp",
    command: ["grok", "agent", "stdio"],
    enabled: false,
    installLink: "https://docs.x.ai/build/overview",
  },
  {
    id: "acp-hermes",
    label: "Hermes",
    engine: "acp",
    command: ["hermes", "acp"],
    enabled: false,
    installLink: "https://hermes-agent.nousresearch.com/docs/user-guide/features/acp",
  },
  {
    id: "acp-junie",
    label: "Junie",
    engine: "acp",
    command: ["junie", "--acp", "true"],
    enabled: false,
    installLink: "https://junie.jetbrains.com/docs/junie-cli-acp.html",
  },
  {
    id: "acp-kilo",
    label: "Kilo",
    engine: "acp",
    command: ["kilo", "acp"],
    enabled: false,
    installLink: "https://kilo.ai/docs/code-with-ai/platforms/cli",
  },
  {
    id: "acp-kiro",
    label: "Kiro CLI",
    engine: "acp",
    command: ["kiro-cli", "acp"],
    enabled: false,
    installLink: "https://kiro.dev/docs/cli/acp/",
  },
  {
    id: "acp-kimi",
    label: "Kimi Code CLI",
    engine: "acp",
    command: ["kimi", "acp"],
    enabled: false,
    installLink: "https://github.com/MoonshotAI/kimi-code",
  },
  {
    id: "acp-minimax-code",
    label: "MiniMax Code",
    engine: "acp",
    command: ["npx", "-y", "@minimax-ai/code@0.1.2", "acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "@minimax-ai/code@0.1.2",
    },
    installLink: "https://agent.minimax.io",
  },
  {
    id: "acp-minion-code",
    label: "Minion Code",
    engine: "acp",
    command: ["uvx", "--from", "minion-code==0.1.44", "minion-code", "acp"],
    enabled: false,
    installLink: "https://github.com/femto/minion-code",
  },
  {
    id: "acp-mistral-vibe",
    label: "Mistral Vibe",
    engine: "acp",
    command: ["vibe-acp"],
    enabled: false,
    installLink: "https://github.com/mistralai/mistral-vibe",
  },
  {
    id: "acp-nova",
    label: "Nova",
    engine: "acp",
    command: ["npx", "-y", "@compass-ai/nova@1.1.29", "acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "@compass-ai/nova@1.1.29",
    },
    installLink: "https://www.compassap.ai/portfolio/nova.html",
  },
  {
    id: "acp-poolside",
    label: "Poolside",
    engine: "acp",
    command: ["pool", "acp"],
    enabled: false,
    installLink: "https://docs.poolside.ai/cli/pool",
  },
  {
    id: "acp-qoder",
    label: "Qoder CLI",
    engine: "acp",
    command: ["npx", "-y", "@qoder-ai/qodercli@1.1.4", "--acp"],
    enabled: false,
    install: {
      kind: "npx",
      package: "@qoder-ai/qodercli@1.1.4",
    },
    installLink: "https://qoder.com",
  },
  {
    id: "acp-qwen-code",
    label: "Qwen Code",
    engine: "acp",
    command: ["npx", "-y", "@qwen-code/qwen-code@0.20.1", "--acp", "--experimental-skills"],
    enabled: false,
    install: {
      kind: "npx",
      package: "@qwen-code/qwen-code@0.20.1",
    },
    installLink: "https://qwenlm.github.io/qwen-code-docs/en/users/overview",
  },
  {
    id: "acp-sigit",
    label: "siGit Code",
    engine: "acp",
    command: ["sigit"],
    enabled: false,
    installLink: "https://github.com/getsigit/sigit",
  },
  {
    id: "acp-stakpak",
    label: "Stakpak",
    engine: "acp",
    command: ["stakpak", "acp"],
    enabled: false,
    installLink: "https://stakpak.dev/",
  },
  {
    id: "acp-traecli",
    label: "TRAE CLI",
    engine: "acp",
    command: ["traecli", "acp", "serve"],
    enabled: false,
    installLink: "https://docs.trae.cn/cli_get-started-with-trae-cli",
  },
  {
    id: "acp-vtcode",
    label: "VT Code",
    engine: "acp",
    command: ["vtcode", "acp"],
    enabled: false,
    installLink: "https://github.com/vinhnx/VTCode/blob/main/docs/guides/zed-acp.md",
    env: {
      VT_ACP_ENABLED: "1",
      VT_ACP_ZED_ENABLED: "1",
    },
  },
];
